name: serene
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  animations: ^1.0.0+5
  flutter_staggered_grid_view: ^0.3.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/city/
    - assets/images/meditation/
    - assets/images/forest/
    - assets/images/rain/
  fonts:
    - family: HaasGrotesk
      fonts:
        - asset: fonts/HaasGrotesk-Regular.ttf
          weight: 400
        - asset: fonts/HaasGrotesk-Medium.ttf
          weight: 500
        - asset: fonts/HaasGrotesk-Bold.ttf
          weight: 700
